App\Entity\Product:
   attributes:
      id:
         groups: [ 'group1', 'group2' ]
      description:
         groups: [ 'group1', 'group2']
      brand:
         groups: [ 'group1' ]
      category:
         groups: [ 'group1' ]
      price:
         groups: [ 'group2' ]